Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder ".", "/git"
  config.vm.provision :shell, path: "configure"
  config.vm.network "private_network", ip: "192.168.50.4"
end
